AWSTemplateFormatVersion: 2010-09-09
Description: Cloud Formation template for custom RDS PostgreSQL 16 - rds-cf-us-east-1-376129860122-sandbox-dlh

Parameters: 
  pEnv:
    Description: The custom Env to stack
    Type: String

  pSolution:
    Description: The custom Env to stack
    Type: String    

  pDBName:
    Default: motorinc_oltp
    Description: The database name
    Type: String

Resources: 
  PostgreSQLSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub secret-oltp-postgres-16-3-rds-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
      Description: "Secrets Manager secret for RDS PostgreSQL instance"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password" # gera senha aleatoria
        PasswordLength: 16
        ExcludeCharacters: '";+%@/\\'

  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: !Sub oltp-postgres-16-3-rds-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
      DBName: !Ref pDBName
      DBParameterGroupName: !Ref rdsDBParameterGroup
      DBSubnetGroupName: !Ref rdsDBSubnetGroup
      Engine: postgres
      EngineVersion: 16.3
      MasterUsername: !Sub '{{resolve:secretsmanager:${PostgreSQLSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${PostgreSQLSecret}::password}}'
      MultiAZ: false
      PubliclyAccessible: true
      VPCSecurityGroups: 
        - sg-0c1a77b79c1918b36
      StorageType: gp3        

  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub Subnet group for RDS database in ${pEnv} for ${pSolution}
      SubnetIds:
        - subnet-01e5ddfa95e9b2cb5 #(us-east-1a)
        - subnet-0dabf657a008ee9dc #(us-east-1b)

  rdsDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub DB Parameter Group for RDS database in ${pEnv} for ${pSolution}
      Family: postgres16
      Parameters:
        rds.logical_replication: 1
        rds.log_retention_period: 1440 

Outputs:
  # Export Secret ARN
  oSecretARN:
      Description: 'ARN of the Secrets Manager secret for PostgreSQL instance'
      Value: !Ref PostgreSQLSecret
      Export:
        Name: !Sub '${AWS::StackName}-oSecretARN'
      #Used in stack  dms
      # to know the generated password it will needed access the secrets manager console

  # Export RDS 
  oRDSDBInstanceEndpoint:
      Description: 'The connection endpoint for the database.'
      Value: !GetAtt 'rdsDBInstance.Endpoint.Address'
      Export:
        Name: !Sub '${AWS::StackName}-oRDSDBInstanceEndpoint'
      # used in dms stack             

