AWSTemplateFormatVersion: 2010-09-09
Description: CF template custom DMS - dms-cf-us-east-1-376129860122-sandbox-dlh

Parameters: 
  pExportS3StackName:
    Description: The name of the s3 stack that exports values
    Type: String

  pExportRolesStackName:
    Description: The name of the iam roles stack that exports values
    Type: String    

  pExportRdsStackName:
    Description: The name of the rds stack that exports values
    Type: String    

  pExportSecretStackName:
    Description: The ARN of the Secrets Manager secret for PostgreSQL instance
    Type: String        

  pEnv:
    Description: The custom Env to stack
    Type: String

  pSolution:
    Description: The custom Env to stack
    Type: String

Resources: 
  vpcEndpointS3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource:
              - '*'
      RouteTableIds:
        - rtb-03a466a54e57aeb85
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: vpc-0fa942f503a866e20

  rReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      AllocatedStorage: 50
      EngineVersion: 3.5.3
      AutoMinorVersionUpgrade: false
      MultiAZ: false
      ReplicationInstanceClass: dms.t3.micro
      ReplicationInstanceIdentifier: !Sub dms-rds-s3-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
      ReplicationSubnetGroupIdentifier: !Ref rReplicationSubnetGroup    
      PubliclyAccessible: false
      VpcSecurityGroupIds: 
        - sg-0c1a77b79c1918b36

  rReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties: 
      ReplicationSubnetGroupDescription: !Sub Subnet group for DMS in ${pEnv} for ${pSolution}
      SubnetIds: 
        - subnet-01e5ddfa95e9b2cb5 #(us-east-1a)
        - subnet-09605eccdcfc3c955 #(us-east-1b)

  rEndpointRDS:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: !Sub endpoint-rds-postgresql-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
      EndpointType: source
      EngineName: postgres
      Username: !Join ['', ['{{resolve:secretsmanager:', Fn::ImportValue: !Sub '${pExportSecretStackName}-oSecretARN', ':SecretString:username}}' ]]
      Password: !Join ['', ['{{resolve:secretsmanager:', Fn::ImportValue: !Sub '${pExportSecretStackName}-oSecretARN', ':SecretString:password}}' ]]
      SslMode: require
      ServerName: !ImportValue
        'Fn::Sub': '${pExportRdsStackName}-oRDSDBInstanceEndpoint'
      Port: 5432
      DatabaseName: motorinc_oltp
      ExtraConnectionAttributes: "heartbeatEnable=Y;heartbeatSchema=public;heartbeatFrequency=15"

  rEndpointS3:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: !Sub endpoint-s3-datalake-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
      EndpointType: target
      EngineName: s3
      ExtraConnectionAttributes: "useTaskStartTimeForFullLoadTimestamp=true;dataFormat=csv;maxFileSize=131072;timestampColumnName=extract_at;addColumnName=true;includeOpForFullLoad=true;cdcMaxBatchInterval=120;cdcMinFileSize=32000"
      S3Settings: 
        BucketFolder: commercial/erp
        BucketName: !ImportValue
          'Fn::Sub': '${pExportS3StackName}-oS3BucketNameBronze'
        CompressionType: GZIP
        CsvDelimiter: "|"
        CsvRowDelimiter: \n
        ServiceAccessRoleArn: !ImportValue
          'Fn::Sub': '${pExportRolesStackName}-oDMSS3Role'

  rReplicationTaskTables:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationTaskIdentifier: !Sub task-ingestion-rds-s3-tables-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
      SourceEndpointArn: !Ref rEndpointRDS
      TargetEndpointArn: !Ref rEndpointS3
      ReplicationInstanceArn: !Ref rReplicationInstance
      MigrationType: full-load #full-load | cdc | full-load-and-cdc > https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Task.CDC.html
      TableMappings: |
        {
          "rules": [
            {
              "rule-type": "selection",
              "rule-id": "1",
              "rule-name": "1",
              "object-locator": {
                      "schema-name": "public",
                      "table-name": "customers"
              },
              "rule-action": "explicit"
            },
            {
              "rule-type": "selection",
              "rule-id": "2",
              "rule-name": "2",
              "object-locator": {
                      "schema-name": "public",
                      "table-name": "employees"
              },
              "rule-action": "explicit"
            },
            {
              "rule-type": "selection",
              "rule-id": "3",
              "rule-name": "3",
              "object-locator": {
                      "schema-name": "public",
                      "table-name": "offices"
              },
              "rule-action": "explicit"
            },
            {
              "rule-type": "selection",
              "rule-id": "4",
              "rule-name": "4",
              "object-locator": {
                      "schema-name": "public",
                      "table-name": "orderdetails"
              },
              "rule-action": "explicit"
            },
            {
              "rule-type": "selection",
              "rule-id": "5",
              "rule-name": "5",
              "object-locator": {
                      "schema-name": "public",
                      "table-name": "orders"
              },
              "rule-action": "explicit"
            }
          ]
        }
      ReplicationTaskSettings: |
        {
          "Logging": {
            "EnableLogging": true,
            "EnableLogContext": false,
            "LogComponents": [
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "DATA_STRUCTURE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "COMMUNICATION"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "IO"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "COMMON"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "FILE_FACTORY"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "FILE_TRANSFER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "REST_SERVER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "ADDONS"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TARGET_LOAD"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TARGET_APPLY"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "SOURCE_UNLOAD"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "SOURCE_CAPTURE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TRANSFORMATION"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "SORTER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TASK_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TABLES_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "METADATA_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "PERFORMANCE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "VALIDATOR_EXT"
              }
            ],
            "LogConfiguration": {
                "TraceOnErrorMb": 10,
                "EnableTraceOnError": false
            },
            "CloudWatchLogGroup": null,
            "CloudWatchLogStream": null
          },
          "StreamBufferSettings": {
            "StreamBufferCount": 3,
            "CtrlStreamBufferSizeInMB": 5,
            "StreamBufferSizeInMB": 8
          },
          "ErrorBehavior": {
            "FailOnNoTablesCaptured": true,
            "ApplyErrorUpdatePolicy": "LOG_ERROR",
            "FailOnTransactionConsistencyBreached": false,
            "RecoverableErrorThrottlingMax": 1800,
            "DataErrorEscalationPolicy": "SUSPEND_TABLE",
            "ApplyErrorEscalationCount": 0,
            "RecoverableErrorStopRetryAfterThrottlingMax": true,
            "RecoverableErrorThrottling": true,
            "ApplyErrorFailOnTruncationDdl": false,
            "DataTruncationErrorPolicy": "LOG_ERROR",
            "ApplyErrorInsertPolicy": "LOG_ERROR",
            "EventErrorPolicy": "IGNORE",
            "ApplyErrorEscalationPolicy": "LOG_ERROR",
            "RecoverableErrorCount": -1,
            "DataErrorEscalationCount": 0,
            "TableErrorEscalationPolicy": "STOP_TASK",
            "RecoverableErrorInterval": 5,
            "ApplyErrorDeletePolicy": "IGNORE_RECORD",
            "TableErrorEscalationCount": 0,
            "FullLoadIgnoreConflicts": true,
            "DataErrorPolicy": "LOG_ERROR",
            "TableErrorPolicy": "SUSPEND_TABLE"
          },
          "TTSettings": null,
          "FullLoadSettings": {
            "CommitRate": 10000,
            "StopTaskCachedChangesApplied": false,
            "StopTaskCachedChangesNotApplied": false,
            "MaxFullLoadSubTasks": 8,
            "TransactionConsistencyTimeout": 600,
            "CreatePkAfterFullLoad": false,
            "TargetTablePrepMode": "DROP_AND_CREATE"
          },
          "TargetMetadata": {
            "ParallelApplyBufferSize": 0,
            "ParallelApplyQueuesPerThread": 0,
            "ParallelApplyThreads": 0,
            "TargetSchema": "",
            "InlineLobMaxSize": 0,
            "ParallelLoadQueuesPerThread": 0,
            "SupportLobs": true,
            "LobChunkSize": 64,
            "TaskRecoveryTableEnabled": false,
            "ParallelLoadThreads": 0,
            "LobMaxSize": 32,
            "BatchApplyEnabled": false,
            "FullLobMode": false,
            "LimitedSizeLobMode": true,
            "LoadMaxFileSize": 0,
            "ParallelLoadBufferSize": 0
          },
          "BeforeImageSettings": null,
          "ControlTablesSettings": {
            "historyTimeslotInMinutes": 5,
            "HistoryTimeslotInMinutes": 5,
            "StatusTableEnabled": false,
            "SuspendedTablesTableEnabled": false,
            "HistoryTableEnabled": false,
            "ControlSchema": "",
            "FullLoadExceptionTableEnabled": false
          },
          "LoopbackPreventionSettings": null,
          "CharacterSetSettings": null,
          "FailTaskWhenCleanTaskResourceFailed": false,
          "ChangeProcessingTuning": {
            "StatementCacheSize": 50,
            "CommitTimeout": 1,
            "BatchApplyPreserveTransaction": true,
            "BatchApplyTimeoutMin": 1,
            "BatchSplitSize": 0,
            "BatchApplyTimeoutMax": 30,
            "MinTransactionSize": 1000,
            "MemoryKeepTime": 60,
            "BatchApplyMemoryLimit": 500,
            "MemoryLimitTotal": 1024
          },
          "ChangeProcessingDdlHandlingPolicy": {
            "HandleSourceTableDropped": true,
            "HandleSourceTableTruncated": true,
            "HandleSourceTableAltered": true
          },
          "PostProcessingRules": null
        }      

  rReplicationTaskProducts:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationTaskIdentifier: !Sub task-ingestion-rds-s3-products-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
      SourceEndpointArn: !Ref rEndpointRDS
      TargetEndpointArn: !Ref rEndpointS3
      ReplicationInstanceArn: !Ref rReplicationInstance
      MigrationType: full-load-and-cdc
      TableMappings: |
        {
          "rules": [
            {
              "rule-type": "selection",
              "rule-id": "1",
              "rule-name": "1",
              "object-locator": {
                "schema-name": "public",
                "table-name": "products"
              },
              "rule-action": "include"
            }
          ]
        }      
      ReplicationTaskSettings: |
        {
          "Logging": {
            "EnableLogging": true,
            "EnableLogContext": false,
            "LogComponents": [
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TRANSFORMATION"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "SOURCE_UNLOAD"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "IO"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TARGET_LOAD"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "PERFORMANCE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "SOURCE_CAPTURE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "SORTER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "REST_SERVER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "VALIDATOR_EXT"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TARGET_APPLY"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TASK_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TABLES_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "METADATA_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "FILE_FACTORY"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "COMMON"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "ADDONS"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "DATA_STRUCTURE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "COMMUNICATION"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "FILE_TRANSFER"
              }
            ],
            "LogConfiguration": {
                    "TraceOnErrorMb": 10,
                    "EnableTraceOnError": false
            }
          },
          "StreamBufferSettings": {
            "StreamBufferCount": 3,
            "CtrlStreamBufferSizeInMB": 5,
            "StreamBufferSizeInMB": 8
          },
          "ErrorBehavior": {
            "FailOnNoTablesCaptured": true,
            "ApplyErrorUpdatePolicy": "LOG_ERROR",
            "FailOnTransactionConsistencyBreached": false,
            "RecoverableErrorThrottlingMax": 1800,
            "DataErrorEscalationPolicy": "SUSPEND_TABLE",
            "ApplyErrorEscalationCount": 0,
            "RecoverableErrorStopRetryAfterThrottlingMax": true,
            "RecoverableErrorThrottling": true,
            "ApplyErrorFailOnTruncationDdl": false,
            "DataTruncationErrorPolicy": "LOG_ERROR",
            "ApplyErrorInsertPolicy": "LOG_ERROR",
            "EventErrorPolicy": "IGNORE",
            "ApplyErrorEscalationPolicy": "LOG_ERROR",
            "RecoverableErrorCount": -1,
            "DataErrorEscalationCount": 0,
            "TableErrorEscalationPolicy": "STOP_TASK",
            "RecoverableErrorInterval": 5,
            "ApplyErrorDeletePolicy": "IGNORE_RECORD",
            "TableErrorEscalationCount": 0,
            "FullLoadIgnoreConflicts": true,
            "DataErrorPolicy": "LOG_ERROR",
            "TableErrorPolicy": "SUSPEND_TABLE"
          },
          "TTSettings": {
            "TTS3Settings": null,
            "TTRecordSettings": null,
            "EnableTT": false
          },
          "FullLoadSettings": {
            "CommitRate": 10000,
            "StopTaskCachedChangesApplied": false,
            "StopTaskCachedChangesNotApplied": false,
            "MaxFullLoadSubTasks": 8,
            "TransactionConsistencyTimeout": 600,
            "CreatePkAfterFullLoad": false,
            "TargetTablePrepMode": "DROP_AND_CREATE"
          },
          "TargetMetadata": {
            "ParallelApplyBufferSize": 0,
            "ParallelApplyQueuesPerThread": 0,
            "ParallelApplyThreads": 0,
            "TargetSchema": "",
            "InlineLobMaxSize": 0,
            "ParallelLoadQueuesPerThread": 0,
            "SupportLobs": true,
            "LobChunkSize": 0,
            "TaskRecoveryTableEnabled": false,
            "ParallelLoadThreads": 0,
            "LobMaxSize": 32,
            "BatchApplyEnabled": false,
            "FullLobMode": false,
            "LimitedSizeLobMode": true,
            "LoadMaxFileSize": 0,
            "ParallelLoadBufferSize": 0
          },
          "BeforeImageSettings": null,
          "ControlTablesSettings": {
            "historyTimeslotInMinutes": 5,
            "HistoryTimeslotInMinutes": 5,
            "StatusTableEnabled": false,
            "SuspendedTablesTableEnabled": false,
            "HistoryTableEnabled": false,
            "ControlSchema": "",
            "FullLoadExceptionTableEnabled": false
          },
          "LoopbackPreventionSettings": null,
          "CharacterSetSettings": null,
          "FailTaskWhenCleanTaskResourceFailed": false,
          "ChangeProcessingTuning": {
            "StatementCacheSize": 50,
            "CommitTimeout": 1,
            "BatchApplyPreserveTransaction": true,
            "BatchApplyTimeoutMin": 1,
            "BatchSplitSize": 0,
            "BatchApplyTimeoutMax": 30,
            "MinTransactionSize": 1000,
            "MemoryKeepTime": 60,
            "BatchApplyMemoryLimit": 500,
            "MemoryLimitTotal": 1024
          },
          "ChangeProcessingDdlHandlingPolicy": {
            "HandleSourceTableDropped": true,
            "HandleSourceTableTruncated": true,
            "HandleSourceTableAltered": true
          },
          "PostProcessingRules": null
        }      
