AWSTemplateFormatVersion: 2010-09-09
Description: CF template for a custom IAM - users-cf-us-east-1-376129860122-sandbox-dlh

Parameters: 
  pExportRdsStackName:
    Description: The name of the rds stack that exports values
    Type: String   

  pExportS3StackName:
    Description: The name of the vpc stack that exports values
    Type: String

  pExportGlueStackName:
    Description: The name of the vpc stack that exports values
    Type: String

  pExportAthenaStackName:
    Description: The name of the vpc stack that exports values
    Type: String

  pEnv:
    Description: The custom Env to stack
    Type: String

  pSolution:
    Description: The custom Env to stack
    Type: String

Resources: 
  rIAMUserDlk:
    Type: AWS::IAM::User  
    Properties: 
      UserName: dlk_admin    
      Policies: 
        - PolicyName: inlineDlkPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:ListAllMyBuckets
                Resource: '*'               
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucketMultipartUploads
                  - s3:AbortMultipartUpload
                  - s3:DeleteObjectVersion
                  - s3:ListBucketVersions
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:GetBucketLocation     
                Resource:                
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameBronze'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameSilver'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameGold'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameAthena'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameBronze'
                      - '/*'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameSilver'
                      - '/*'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameGold'
                      - '/*'
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameAthena'
                      - '/*'                 
              - Effect: Allow
                Action:
                  - glue:*
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:glue:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':database/'
                      - Fn::ImportValue: !Sub '${pExportGlueStackName}-oGlueDatabaseDwh'
                  - !Join
                    - ''
                    - - 'arn:aws:glue:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':table/'
                      - Fn::ImportValue: !Sub '${pExportGlueStackName}-oGlueDatabaseDwh'
                      - '/*'              
                  - !Join
                    - ''
                    - - 'arn:aws:glue:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':database/'
                      - Fn::ImportValue: !Sub '${pExportGlueStackName}-oGlueDatabaseOds'
                  - !Join
                    - ''
                    - - 'arn:aws:glue:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':table/'
                      - Fn::ImportValue: !Sub '${pExportGlueStackName}-oGlueDatabaseOds'
                      - '/*'                              
                  - !Join
                    - ''
                    - - 'arn:aws:glue:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':catalog'                        
              - Effect: Allow
                Action: athena:ListDataCatalogs
                Resource: '*'  
              - Effect: Allow
                Action:
                  - athena:*
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:athena:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':datacatalog/AwsDataCatalog'
                  - !Join
                    - ''
                    - - 'arn:aws:athena:'
                      - !Ref AWS::Region
                      - ':'
                      - !Ref AWS::AccountId
                      - ':workgroup/'
                      - Fn::ImportValue: !Sub '${pExportAthenaStackName}-oAthenaWorkGroup'
              - Effect: Allow
                Action:
                  - secretsmanager:*
                Resource: 
                  - Fn::ImportValue: !Sub ${pExportRdsStackName}-oSecretARN

  rIAMAccessKeyDlk:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref rIAMUserDlk

Outputs:
  oAccessDlkKey:
    Value: !Ref rIAMAccessKeyDlk
    Description: AWSAccessKeyId of dlk_admin user

  oSecretDlkKey:
    Value: !GetAtt rIAMAccessKeyDlk.SecretAccessKey
    Description: AWSSecretAccessKey of dlk_admin user