name: 'Deploy para o CloudFormation'

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

    if: "!contains(github.event.head_commit.message, '[skip ci]')" #commit message must not contain [skip ci] to run CI
    
    steps:
      - name: Connect to the repository
        uses: actions/checkout@v4 #https://github.com/actions/checkout

      #Configure AWS Credential
      - name: Step Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      # Deploy CloudFormation S3 Stack
      - name: Action AWS CloudFormation "Deploy CloudFormation S3 Stack"
        if: "contains(github.event.head_commit.message, '[s3]')" # only executes when the commit message contains [s3]
        uses: aws-actions/aws-cloudformation-github-deploy@v1 #https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions
        with:
          name: s3-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 03_s3.yml
          no-fail-on-empty-changeset: 1
          parameter-overrides: >-
            pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}  

      # Deploy CloudFormation RDS Stack
      - name: Action AWS CloudFormation "RDS CloudFormation Deploy"
        if: "contains(github.event.head_commit.message, '[rds]')" # only executes when the commit message contains [rds]
        uses: aws-actions/aws-cloudformation-github-deploy@v1 #https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions
        with:
          name: rds-cf-${{ vars.AWS_DEFAULT_REGION }}-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_ENV }}-${{ vars.AWS_SOLUTION }}
          template: 04_rds.yml
          no-fail-on-empty-changeset: 1      
          parameter-overrides: >-
            pEnv=${{ vars.AWS_ENV }}
            ,pSolution=${{ vars.AWS_SOLUTION }}  