name: 'Deploy para o CloudFormation'

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

    if: "!contains(github.event.head_commit.message, '[skip ci]')" #commit message must not contain [skip ci] to run CI
    
    steps:
      - name: Connect to the repository
        uses: actions/checkout@v4 #https://github.com/actions/checkout

      #Configure AWS Credential
      - name: Step Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}